variables:
    DOCKER_HOST: tcp://localhost:2375/
    DOCKER_DRIVER: overlay2
    KUBECONFIG: /etc/deploy/config
    DOCKER_TLS_CERTDIR: "" 

stages:
    - build
    - test
    - deploy

default:
    image: node:12.14-alpine
    cache: &global_cache
        key: ${$CI_PROJECT_ID}
        paths:
            - node_modules/
            - .yarn
        policy: pull

build webapp:
    image: node:12.14-alpine
    stage: build
    cache:
        <<: *global_cache
        policy: pull-push
    script:
        - yarn install --pure-lockfile --cache-folder .yarn
        - sh scripts/build-dist.sh
    artifacts:
        expire_in: 1 week
        paths:
            - dist
